# Loading Packages
message("Loading packages from .Rprofile...")
library("configr")
library("ggplot2")
library("purrr")
library("shiny")
library("shinyWidgets")
library("shinydashboard")
library("stringr")
library("svglite")
library("tibble")
library("dplyr", include.only = c("rename", "select"))
library("glue", include.only = c("glue"))
library("graphics", include.only = c("abline", "legend", "lines", "mtext", "par", "rect", "text"))
library("grDevices", include.only = c("dev.off"))
library("magrittr", include.only = c("%>%"))
library("rlang", include.only = c("env", "env_names", "env_print", "new_environment"))
library("stats", include.only = c("predict", "sd"))
library("tibble", include.only = c("as_tibble"))
library("utils", include.only = c("str"))
library("utils", include.only = c("capture.output", "data", "help", "packageVersion", "str"))
library("shinycssloaders", include.only = c("withSpinner"))
library("memoise", include.only = c("memoise"))
library("toscmask", include.only = c("*", "+"))
