dbms:
  # type: postgres
  # hostname: localhost
  # port: 5432
  # database: imluidb
  # username: testuser
  # password: K59#vnUPP4Q#
  type: sqlite
  filepath: ${IMLUI_CONFIG_DIR}/imlui_settings.sqlite
